processes:
  traefik:
    path: /home/nonroot/traefik
    type: service
  certwatcher:
    path: /home/nonroot/certwatcher
    type: ticker
    ticker: "@every 5s"
    run_at_start: true
    enabled: false
  accesslogexporter:
    path: /home/nonroot/access-log-exporter
    type: ticker
    ticker: "@every 5s"
    enabled: false
    on_failure: continue
    hide_label: true
