name: crowdsec-build

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - crowdsec/docker-bake.hcl
  pull_request:
    paths:
      - crowdsec/docker-bake.hcl

permissions:
  contents: write
  packages: write

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check.outputs.exists }}
    steps:
      - uses: actions/checkout@v7
      - id: check
        uses: ./.github/common/tag-exists
        with:
          container: crowdsec

  build:
    needs: preflight
    if: ${{ needs.preflight.outputs.exists != 'true' || github.event_name != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: ./.github/common/build
        with:
          container: crowdsec
          push: ${{ github.event_name != 'pull_request' }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/common/scan
        if: ${{ github.event_name != 'pull_request' }}
        with:
          image: crowdsec:latest
          warn-files: usr/local/bin/crowdsec,usr/local/bin/cscli
      - uses: ./.github/common/tag
        if: ${{ github.event_name != 'pull_request' }}
        with:
          container: crowdsec
          app-id: ${{ vars.EXTRA_ADMIN_APP_ID }}
          private-key: ${{ secrets.EXTRA_ADMIN_PRIVATE_KEY }}
