name: trivy-crowdsec

on:
  schedule:
    - cron: '15 5 * * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  scan:
    uses: ./.github/workflows/trivy.yml
    with:
      image: crowdsec
